const StudentData = [
  {"id": 101 ,   "name": "Evelyn", "assignment": "W4D1-Scrum",  "ratingDifficulty": 3, "ratingFun": 4},
  {"id": 102 ,   "name": "Evelyn", "assignment": "W1D1-1", "ratingDifficulty": 3, "ratingFun": 3},
  { "id": 103 ,  "name": "Evelyn", "assignment": "W1D2-1", "ratingDifficulty": 1, "ratingFun": 3 },
  { "id": 104 ,  "name": "Evelyn", "assignment": "W1D2-2", "ratingDifficulty": 1, "ratingFun": 4 },
  { "id": 105 ,  "name": "Evelyn", "assignment": "W1D2-3", "ratingDifficulty": 2, "ratingFun": 3 },
  { "id": 106 ,  "name": "Evelyn", "assignment": "W1D2-4", "ratingDifficulty": 3, "ratingFun": 4 },
  { "id": 107 ,  "name": "Evelyn", "assignment": "W1D2-5", "ratingDifficulty": 3, "ratingFun": 4 },
  { "id": 108 ,  "name": "Evelyn", "assignment": "W1D3-1", "ratingDifficulty": 3, "ratingFun": 4 },
  { "id": 109 ,  "name": "Evelyn", "assignment": "W1D3-2", "ratingDifficulty": 3, "ratingFun": 4 },
  { "id": 111 ,  "name": "Evelyn", "assignment": "W1D3-4", "ratingDifficulty": 4, "ratingFun": 4 },
  { "id": 112 ,  "name": "Evelyn", "assignment": "W1D3-5", "ratingDifficulty": 4, "ratingFun": 4 },
  { "id": 113 ,  "name": "Evelyn", "assignment": "W1D3 - Project - Guess-the-number", "ratingDifficulty": 5, "ratingFun": 5 },
  { "id": 114 ,  "name": "Evelyn", "assignment": "W1D4-1", "ratingDifficulty": 4, "ratingFun": 5 },
  { "id": 115 ,  "name": "Evelyn", "assignment": "W1D4 - Project - Kleurentoggle", "ratingDifficulty": 3, "ratingFun": 4 },
  { "id": 116 ,  "name": "Evelyn", "assignment": "W1D5 - Project - Galgje", "ratingDifficulty": 4, "ratingFun": 3 },
  { "id": 117 ,  "name": "Evelyn", "assignment": "W2D1-1", "ratingDifficulty": 1, "ratingFun": 5 },
  { "id": 118 ,  "name": "Evelyn", "assignment": "W2D1-2", "ratingDifficulty": 2, "ratingFun": 5 },
  { "id": 119 ,  "name": "Evelyn", "assignment": "W2D2-1", "ratingDifficulty": 3, "ratingFun": 4 },
  { "id": 120 ,  "name": "Evelyn", "assignment": "W2D2-2", "ratingDifficulty": 3, "ratingFun": 4 },
  { "id": 121 ,  "name": "Evelyn", "assignment": "W2D2-3", "ratingDifficulty": 3, "ratingFun": 4 },
  { "id": 122 ,  "name": "Evelyn", "assignment": "W2D3-1", "ratingDifficulty": 4, "ratingFun": 4 },
  { "id": 123 ,  "name": "Evelyn", "assignment": "W2D3-2", "ratingDifficulty": 1, "ratingFun": 3 },
  { "id": 124 ,  "name": "Evelyn", "assignment": "W2D3-3", "ratingDifficulty": 4, "ratingFun": 4 },
  { "id": 125 ,  "name": "Evelyn", "assignment": "W2D4-1", "ratingDifficulty": 1, "ratingFun": 3 },
  { "id": 126 ,  "name": "Evelyn", "assignment": "W2D4-2", "ratingDifficulty": 4, "ratingFun": 4 },
  { "id": 127 ,  "name": "Evelyn", "assignment": "W2D4-3", "ratingDifficulty": 1, "ratingFun": 3 },
  { "id": 128 ,  "name": "Evelyn", "assignment": "W2D5 - Project - Filmzoeker", "ratingDifficulty": 3, "ratingFun": 4 },
  { "id": 129 ,  "name": "Evelyn", "assignment": "W3D1-1", "ratingDifficulty": 3, "ratingFun": 4 },
  { "id": 130 ,  "name": "Evelyn", "assignment": "W3D1-2", "ratingDifficulty": 2, "ratingFun": 4 },
  { "id": 131 ,  "name": "Evelyn", "assignment": "W3D1-3", "ratingDifficulty": 3, "ratingFun": 4 },
  { "id": 132 ,  "name": "Evelyn", "assignment": "W3D1-4", "ratingDifficulty": 3, "ratingFun": 3 },
  { "id": 133 ,  "name": "Evelyn", "assignment": "W3D2-1", "ratingDifficulty": 2, "ratingFun": 4 },
  { "id": 134 ,  "name": "Evelyn", "assignment": "W3D2-2", "ratingDifficulty": 3, "ratingFun": 3 },
  { "id": 135 ,  "name": "Evelyn", "assignment": "W3D2-3", "ratingDifficulty": 3, "ratingFun": 5 },
  { "id": 136 ,  "name": "Evelyn", "assignment": "W3D3-1", "ratingDifficulty": 4, "ratingFun": 4 },
  { "id": 137 ,  "name": "Evelyn", "assignment": "W3D3-2", "ratingDifficulty": 4, "ratingFun": 5 },
  { "id": 138 ,  "name": "Evelyn", "assignment": "W3D3-3", "ratingDifficulty": 3, "ratingFun": 5 },
  { "id": 139 ,  "name": "Evelyn", "assignment": "W3D3-4", "ratingDifficulty": 4, "ratingFun": 5 },
  { "id": 140 ,  "name": "Evelyn", "assignment": "W3D4-1", "ratingDifficulty": 5, "ratingFun": 5 },
  { "id": 141 ,  "name": "Evelyn", "assignment": "W3D4-2", "ratingDifficulty": 1, "ratingFun": 5 },
  { "id": 142 ,  "name": "Evelyn", "assignment": "W3D5- Project Todo-List", "ratingDifficulty": 2, "ratingFun": 5 },
  { "id": 143 ,  "name": "Evelyn", "assignment": "W4D2-1", "ratingDifficulty": 1, "ratingFun": 5 },
  { "id": 144 ,  "name": "Evelyn", "assignment": "W4D2-2", "ratingDifficulty": 1, "ratingFun": 5 },
  { "id": 145 ,  "name": "Evelyn", "assignment": "W4D2-3", "ratingDifficulty": 1, "ratingFun": 5 },
  { "id": 146 ,  "name": "Evelyn", "assignment": "W4D2-4", "ratingDifficulty": 1, "ratingFun": 5 },
  { "id": 147 ,  "name": "Evelyn", "assignment": "W4D3-1", "ratingDifficulty": 1, "ratingFun": 5 },
  { "id": 148 ,  "name": "Evelyn", "assignment": "W4D3-2", "ratingDifficulty": 1, "ratingFun": 5 },
  { "id": 149 ,  "name": "Evelyn", "assignment": "W4D3-3", "ratingDifficulty": 1, "ratingFun": 5 },
  { "id": 150 ,  "name": "Evelyn", "assignment": "W4D3-4", "ratingDifficulty": 1, "ratingFun": 5 },
  { "id": 151 ,  "name": "Evelyn", "assignment": "W4D3-5", "ratingDifficulty": 1, "ratingFun": 5 },
  { "id": 152 ,  "name": "Evelyn", "assignment": "W4D3 - Project - Next-Level CSS", "ratingDifficulty": 1, "ratingFun": 5 },
  { "id": 153 ,  "name": "Evelyn", "assignment": "W5D4-1", "ratingDifficulty": 3, "ratingFun": 4 },
  { "id": 154 ,  "name": "Evelyn", "assignment": "W5D5 - Project - Lil_Playlist", "ratingDifficulty": 4, "ratingFun": 5 },
  { "id": 155 ,  "name": "Evelyn", "assignment": "W6D1-1", "ratingDifficulty": 5, "ratingFun": 5 },
  { "id": 156 ,  "name": "Evelyn", "assignment": "W6D2-1", "ratingDifficulty": 4, "ratingFun": 5 },
  { "id": 157 ,  "name": "Evelyn", "assignment": "W6D2 - Project - Eindopdracht", "ratingDifficulty": 5, "ratingFun": 5 },
  { "id": 201 ,  "name": "Aranka", "assignment": "W4D1-Scrum", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 202 ,  "name": "Aranka", "assignment": "W1D1-1", "ratingDifficulty": 4, "ratingFun": 3},
  { "id": 203 ,  "name": "Aranka", "assignment": "W1D2-1", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 204 ,  "name": "Aranka", "assignment": "W1D2-2", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 205 ,  "name": "Aranka", "assignment": "W1D2-3", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 206 ,  "name": "Aranka", "assignment": "W1D2-4", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 207 ,  "name": "Aranka", "assignment": "W1D2-5", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 208 ,  "name": "Aranka", "assignment": "W1D3-1", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 209 ,  "name": "Aranka", "assignment": "W1D3-2", "ratingDifficulty": 2, "ratingFun":  1},  
  { "id": 211 ,  "name": "Aranka", "assignment": "W1D3-4", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 212 ,  "name": "Aranka", "assignment": "W1D3-5", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 213 ,  "name": "Aranka", "assignment": "W1D3 - Project - Guess-the-number", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 214 ,  "name": "Aranka", "assignment": "W1D4-1", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 215 ,  "name": "Aranka", "assignment": "W1D4 - Project - Kleurentoggle", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 216 ,  "name": "Aranka", "assignment": "W1D5 - Project - Galgje", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 217 ,  "name": "Aranka", "assignment": "W2D1-1", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 218 ,  "name": "Aranka", "assignment": "W2D1-2", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 219 ,  "name": "Aranka", "assignment": "W2D2-1", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 220 ,  "name": "Aranka", "assignment": "W2D2-2", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 221 ,  "name": "Aranka", "assignment": "W2D2-3", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 222 ,  "name": "Aranka", "assignment": "W2D3-1", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 223 ,  "name": "Aranka", "assignment": "W2D3-2", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 224 ,  "name": "Aranka", "assignment": "W2D3-3", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 225 ,  "name": "Aranka", "assignment": "W2D4-1", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 226 ,  "name": "Aranka", "assignment": "W2D4-2", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 227 ,  "name": "Aranka", "assignment": "W2D4-3", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 228 ,  "name": "Aranka", "assignment": "W2D5 - Project - Filmzoeker", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 229 ,  "name": "Aranka", "assignment": "W3D1-1", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 230 ,  "name": "Aranka", "assignment": "W3D1-2", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 231 ,  "name": "Aranka", "assignment": "W3D1-3", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 232 ,  "name": "Aranka", "assignment": "W3D1-4", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 233 ,  "name": "Aranka", "assignment": "W3D2-1", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 234 ,  "name": "Aranka", "assignment": "W3D2-2", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 235 ,  "name": "Aranka", "assignment": "W3D2-3", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 236 ,  "name": "Aranka", "assignment": "W3D3-1", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 237 ,  "name": "Aranka", "assignment": "W3D3-2", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 238 ,  "name": "Aranka", "assignment": "W3D3-3", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 239 ,  "name": "Aranka", "assignment": "W3D3-4", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 240 ,  "name": "Aranka", "assignment": "W3D4-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 241 ,  "name": "Aranka", "assignment": "W3D4-2", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 242 ,  "name": "Aranka", "assignment": "W3D5- Project Todo-List", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 243 ,  "name": "Aranka", "assignment": "W4D2-1", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 244 ,  "name": "Aranka", "assignment": "W4D2-2", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 245 ,  "name": "Aranka", "assignment": "W4D2-3", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 246 ,  "name": "Aranka", "assignment": "W4D2-4", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 247 ,  "name": "Aranka", "assignment": "W4D3-1", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 248 ,  "name": "Aranka", "assignment": "W4D3-2", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 249 ,  "name": "Aranka", "assignment": "W4D3-3", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 250 ,  "name": "Aranka", "assignment": "W4D3-4", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 251 ,  "name": "Aranka", "assignment": "W4D3-5", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 252 ,  "name": "Aranka", "assignment": "W4D3 - Project - Next-Level CSS", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 253 ,  "name": "Aranka", "assignment": "W5D4-1", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 254 ,  "name": "Aranka", "assignment": "W5D5 - Project - Lil_Playlist", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 255 ,  "name": "Aranka", "assignment": "W6D1-1", "ratingDifficulty": 1, "ratingFun": 1 },
  { "id": 256 ,  "name": "Aranka", "assignment": "W6D2-1", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 257 ,  "name": "Aranka", "assignment": "W6D2 - Project - Eindopdracht", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 301 ,  "name": "Floris", "assignment": "W4D1-Scrum", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 302 ,  "name": "Floris", "assignment": "W1D1-1", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 303 ,  "name": "Floris", "assignment": "W1D2-1", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 304 ,  "name": "Floris", "assignment": "W1D2-2", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 305 ,  "name": "Floris", "assignment": "W1D2-3", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 306 ,  "name": "Floris", "assignment": "W1D2-4", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 307 ,  "name": "Floris", "assignment": "W1D2-5", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 308 ,  "name": "Floris", "assignment": "W1D3-1", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 309 ,  "name": "Floris", "assignment": "W1D3-2", "ratingDifficulty": 4, "ratingFun":  4},  
  { "id": 311 ,  "name": "Floris", "assignment": "W1D3-4", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 312 ,  "name": "Floris", "assignment": "W1D3-5", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 313 ,  "name": "Floris", "assignment": "W1D3 - Project - Guess-the-number", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 314 ,  "name": "Floris", "assignment": "W1D4-1", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 315 ,  "name": "Floris", "assignment": "W1D4 - Project - Kleurentoggle", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 316 ,  "name": "Floris", "assignment": "W1D5 - Project - Galgje", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 317 ,  "name": "Floris", "assignment": "W2D1-1", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 318 ,  "name": "Floris", "assignment": "W2D1-2", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 319 ,  "name": "Floris", "assignment": "W2D2-1", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 320 ,  "name": "Floris", "assignment": "W2D2-2", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 321 ,  "name": "Floris", "assignment": "W2D2-3", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 322 ,  "name": "Floris", "assignment": "W2D3-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 323 ,  "name": "Floris", "assignment": "W2D3-2", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 324 ,  "name": "Floris", "assignment": "W2D3-3", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 325 ,  "name": "Floris", "assignment": "W2D4-1", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 326 ,  "name": "Floris", "assignment": "W2D4-2", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 327 ,  "name": "Floris", "assignment": "W2D4-3", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 328 ,  "name": "Floris", "assignment": "W2D5 - Project - Filmzoeker", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 329 ,  "name": "Floris", "assignment": "W3D1-1", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 330 ,  "name": "Floris", "assignment": "W3D1-2", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 331 ,  "name": "Floris", "assignment": "W3D1-3", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 332 ,  "name": "Floris", "assignment": "W3D1-4", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 333 ,  "name": "Floris", "assignment": "W3D2-1", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 334 ,  "name": "Floris", "assignment": "W3D2-2", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 335 ,  "name": "Floris", "assignment": "W3D2-3", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 336 ,  "name": "Floris", "assignment": "W3D3-1", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 337 ,  "name": "Floris", "assignment": "W3D3-2", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 338 ,  "name": "Floris", "assignment": "W3D3-3", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 339 ,  "name": "Floris", "assignment": "W3D3-4", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 340 ,  "name": "Floris", "assignment": "W3D4-1", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 341 ,  "name": "Floris", "assignment": "W3D4-2", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 342 ,  "name": "Floris", "assignment": "W3D5- Project Todo-List", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 343 ,  "name": "Floris", "assignment": "W4D2-1", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 344 ,  "name": "Floris", "assignment": "W4D2-2", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 345 ,  "name": "Floris", "assignment": "W4D2-3", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 346 ,  "name": "Floris", "assignment": "W4D2-4", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 347 ,  "name": "Floris", "assignment": "W4D3-1", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 348 ,  "name": "Floris", "assignment": "W4D3-2", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 349 ,  "name": "Floris", "assignment": "W4D3-3", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 350 ,  "name": "Floris", "assignment": "W4D3-4", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 351 ,  "name": "Floris", "assignment": "W4D3-5", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 352 ,  "name": "Floris", "assignment": "W4D3 - Project - Next-Level CSS", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 353 ,  "name": "Floris", "assignment": "W5D4-1", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 354 ,  "name": "Floris", "assignment": "W5D5 - Project - Lil_Playlist", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 355 ,  "name": "Floris", "assignment": "W6D1-1", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 356 ,  "name": "Floris", "assignment": "W6D2-1", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 357 ,  "name": "Floris", "assignment": "W6D2 - Project - Eindopdracht", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 401 ,  "name": "Hector", "assignment": "W4D1-Scrum", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 402 ,  "name": "Hector", "assignment": "W1D1-1", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 403 ,  "name": "Hector", "assignment": "W1D2-1", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 404 ,  "name": "Hector", "assignment": "W1D2-2", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 405 ,  "name": "Hector", "assignment": "W1D2-3", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 406 ,  "name": "Hector", "assignment": "W1D2-4", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 407 ,  "name": "Hector", "assignment": "W1D2-5", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 408 ,  "name": "Hector", "assignment": "W1D3-1", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 409 ,  "name": "Hector", "assignment": "W1D3-2", "ratingDifficulty": 4, "ratingFun":  3},  
  { "id": 411 ,  "name": "Hector", "assignment": "W1D3-4", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 412 ,  "name": "Hector", "assignment": "W1D3-5", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 413 ,  "name": "Hector", "assignment": "W1D3 - Project - Guess-the-number", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 414 ,  "name": "Hector", "assignment": "W1D4-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 415 ,  "name": "Hector", "assignment": "W1D4 - Project - Kleurentoggle", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 416 ,  "name": "Hector", "assignment": "W1D5 - Project - Galgje", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 417 ,  "name": "Hector", "assignment": "W2D1-1", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 418 ,  "name": "Hector", "assignment": "W2D1-2", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 419 ,  "name": "Hector", "assignment": "W2D2-1", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 420 ,  "name": "Hector", "assignment": "W2D2-2", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 421 ,  "name": "Hector", "assignment": "W2D2-3", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 422 ,  "name": "Hector", "assignment": "W2D3-1", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 423 ,  "name": "Hector", "assignment": "W2D3-2", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 424 ,  "name": "Hector", "assignment": "W2D3-3", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 425 ,  "name": "Hector", "assignment": "W2D4-1", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 426 ,  "name": "Hector", "assignment": "W2D4-2", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 427 ,  "name": "Hector", "assignment": "W2D4-3", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 428 ,  "name": "Hector", "assignment": "W2D5 - Project - Filmzoeker", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 429 ,  "name": "Hector", "assignment": "W3D1-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 430 ,  "name": "Hector", "assignment": "W3D1-2", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 431 ,  "name": "Hector", "assignment": "W3D1-3", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 432 ,  "name": "Hector", "assignment": "W3D1-4", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 433 ,  "name": "Hector", "assignment": "W3D2-1", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 434 ,  "name": "Hector", "assignment": "W3D2-2", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 435 ,  "name": "Hector", "assignment": "W3D2-3", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 436 ,  "name": "Hector", "assignment": "W3D3-1", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 437 ,  "name": "Hector", "assignment": "W3D3-2", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 438 ,  "name": "Hector", "assignment": "W3D3-3", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 439 ,  "name": "Hector", "assignment": "W3D3-4", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 440 ,  "name": "Hector", "assignment": "W3D4-1", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 441 ,  "name": "Hector", "assignment": "W3D4-2", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 442 ,  "name": "Hector", "assignment": "W3D5- Project Todo-List", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 443 ,  "name": "Hector", "assignment": "W4D2-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 444 ,  "name": "Hector", "assignment": "W4D2-2", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 445 ,  "name": "Hector", "assignment": "W4D2-3", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 446 ,  "name": "Hector", "assignment": "W4D2-4", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 447 ,  "name": "Hector", "assignment": "W4D3-1", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 448 ,  "name": "Hector", "assignment": "W4D3-2", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 449 ,  "name": "Hector", "assignment": "W4D3-3", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 450 ,  "name": "Hector", "assignment": "W4D3-4", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 451 ,  "name": "Hector", "assignment": "W4D3-5", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 452 ,  "name": "Hector", "assignment": "W4D3 - Project - Next-Level CSS", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 453 ,  "name": "Hector", "assignment": "W5D4-1", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 454 ,  "name": "Hector", "assignment": "W5D5 - Project - Lil_Playlist", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 455 ,  "name": "Hector", "assignment": "W6D1-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 456 ,  "name": "Hector", "assignment": "W6D2-1", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 457 ,  "name": "Hector", "assignment": "W6D2 - Project - Eindopdracht", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 501 ,  "name": "Martina", "assignment": "W4D1-Scrum", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 502 ,  "name": "Martina", "assignment": "W1D1-1", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 503 ,  "name": "Martina", "assignment": "W1D2-1", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 504 ,  "name": "Martina", "assignment": "W1D2-2", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 505 ,  "name": "Martina", "assignment": "W1D2-3", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 506 ,  "name": "Martina", "assignment": "W1D2-4", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 507 ,  "name": "Martina", "assignment": "W1D2-5", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 508 ,  "name": "Martina", "assignment": "W1D3-1", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 509 ,  "name": "Martina", "assignment": "W1D3-2", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 491 ,  "name": "Martina", "assignment": "W1D3-4", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 492 ,  "name": "Martina", "assignment": "W1D3-5", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 493 ,  "name": "Martina", "assignment": "W1D3 - Project - Guess-the-number", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 494 ,  "name": "Martina", "assignment": "W1D4-1", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 495 ,  "name": "Martina", "assignment": "W1D4 - Project - Kleurentoggle", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 496 ,  "name": "Martina", "assignment": "W1D5 - Project - Galgje", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 497 ,  "name": "Martina", "assignment": "W2D1-1", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 498 ,  "name": "Martina", "assignment": "W2D1-2", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 499 ,  "name": "Martina", "assignment": "W2D2-1", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 500 ,  "name": "Martina", "assignment": "W2D2-2", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 501 ,  "name": "Martina", "assignment": "W2D2-3", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 502 ,  "name": "Martina", "assignment": "W2D3-1", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 503 ,  "name": "Martina", "assignment": "W2D3-2", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 504 ,  "name": "Martina", "assignment": "W2D3-3", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 505 ,  "name": "Martina", "assignment": "W2D4-1", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 506 ,  "name": "Martina", "assignment": "W2D4-2", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 507 ,  "name": "Martina", "assignment": "W2D4-3", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 508 ,  "name": "Martina", "assignment": "W2D5 - Project - Filmzoeker", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 509 ,  "name": "Martina", "assignment": "W3D1-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 510 ,  "name": "Martina", "assignment": "W3D1-2", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 511 ,  "name": "Martina", "assignment": "W3D1-3", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 512 ,  "name": "Martina", "assignment": "W3D1-4", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 513 ,  "name": "Martina", "assignment": "W3D2-1", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 514 ,  "name": "Martina", "assignment": "W3D2-2", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 515 ,  "name": "Martina", "assignment": "W3D2-3", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 516 ,  "name": "Martina", "assignment": "W3D3-1", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 517 ,  "name": "Martina", "assignment": "W3D3-2", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 518 ,  "name": "Martina", "assignment": "W3D3-3", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 519 ,  "name": "Martina", "assignment": "W3D3-4", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 520 ,  "name": "Martina", "assignment": "W3D4-1", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 521 ,  "name": "Martina", "assignment": "W3D4-2", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 522 ,  "name": "Martina", "assignment": "W3D5- Project Todo-List", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 523 ,  "name": "Martina", "assignment": "W4D2-1", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 524 ,  "name": "Martina", "assignment": "W4D2-2", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 525 ,  "name": "Martina", "assignment": "W4D2-3", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 526 ,  "name": "Martina", "assignment": "W4D2-4", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 527 ,  "name": "Martina", "assignment": "W4D3-1", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 528 ,  "name": "Martina", "assignment": "W4D3-2", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 529 ,  "name": "Martina", "assignment": "W4D3-3", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 530 ,  "name": "Martina", "assignment": "W4D3-4", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 531 ,  "name": "Martina", "assignment": "W4D3-5", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 532 ,  "name": "Martina", "assignment": "W4D3 - Project - Next-Level CSS", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 535 ,  "name": "Martina", "assignment": "W5D4-1", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 536 ,  "name": "Martina", "assignment": "W5D5 - Project - Lil_Playlist", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 537 ,  "name": "Martina", "assignment": "W6D1-1", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 538 ,  "name": "Martina", "assignment": "W6D2-1", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 539 ,  "name": "Martina", "assignment": "W6D2 - Project - Eindopdracht", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 601 ,  "name": "Maurits", "assignment": "W4D1-Scrum", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 602 ,  "name": "Maurits", "assignment": "W1D1-1", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 603 ,  "name": "Maurits", "assignment": "W1D2-1", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 604 ,  "name": "Maurits", "assignment": "W1D2-2", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 605 ,  "name": "Maurits", "assignment": "W1D2-3", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 606 ,  "name": "Maurits", "assignment": "W1D2-4", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 607 ,  "name": "Maurits", "assignment": "W1D2-5", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 608 ,  "name": "Maurits", "assignment": "W1D3-1", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 609 ,  "name": "Maurits", "assignment": "W1D3-2", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 611 ,  "name": "Maurits", "assignment": "W1D3-4", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 612 ,  "name": "Maurits", "assignment": "W1D3-5", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 613 ,  "name": "Maurits", "assignment": "W1D3 - Project - Guess-the-number", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 614 ,  "name": "Maurits", "assignment": "W1D4-1", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 615 ,  "name": "Maurits", "assignment": "W1D4 - Project - Kleurentoggle", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 616 ,  "name": "Maurits", "assignment": "W1D5 - Project - Galgje", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 617 ,  "name": "Maurits", "assignment": "W2D1-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 618 ,  "name": "Maurits", "assignment": "W2D1-2", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 619 ,  "name": "Maurits", "assignment": "W2D2-1", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 620 ,  "name": "Maurits", "assignment": "W2D2-2", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 621 ,  "name": "Maurits", "assignment": "W2D2-3", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 622 ,  "name": "Maurits", "assignment": "W2D3-1", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 623 ,  "name": "Maurits", "assignment": "W2D3-2", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 624 ,  "name": "Maurits", "assignment": "W2D3-3", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 625 ,  "name": "Maurits", "assignment": "W2D4-1", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 626 ,  "name": "Maurits", "assignment": "W2D4-2", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 627 ,  "name": "Maurits", "assignment": "W2D4-3", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 628 ,  "name": "Maurits", "assignment": "W2D5 - Project - Filmzoeker", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 629 ,  "name": "Maurits", "assignment": "W3D1-1", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 630 ,  "name": "Maurits", "assignment": "W3D1-2", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 631 ,  "name": "Maurits", "assignment": "W3D1-3", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 632 ,  "name": "Maurits", "assignment": "W3D1-4", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 633 ,  "name": "Maurits", "assignment": "W3D2-1", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 634 ,  "name": "Maurits", "assignment": "W3D2-2", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 635 ,  "name": "Maurits", "assignment": "W3D2-3", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 636 ,  "name": "Maurits", "assignment": "W3D3-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 637 ,  "name": "Maurits", "assignment": "W3D3-2", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 638 ,  "name": "Maurits", "assignment": "W3D3-3", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 639 ,  "name": "Maurits", "assignment": "W3D3-4", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 640 ,  "name": "Maurits", "assignment": "W3D4-1", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 641 ,  "name": "Maurits", "assignment": "W3D4-2", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 642 ,  "name": "Maurits", "assignment": "W3D5- Project Todo-List", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 643 ,  "name": "Maurits", "assignment": "W4D2-1", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 644 ,  "name": "Maurits", "assignment": "W4D2-2", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 645 ,  "name": "Maurits", "assignment": "W4D2-3", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 646 ,  "name": "Maurits", "assignment": "W4D2-4", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 647 ,  "name": "Maurits", "assignment": "W4D3-1", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 648 ,  "name": "Maurits", "assignment": "W4D3-2", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 649 ,  "name": "Maurits", "assignment": "W4D3-3", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 650 ,  "name": "Maurits", "assignment": "W4D3-4", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 651 ,  "name": "Maurits", "assignment": "W4D3-5", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 652 ,  "name": "Maurits", "assignment": "W4D3 - Project - Next-Level CSS", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 653 ,  "name": "Maurits", "assignment": "W5D4-1", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 654 ,  "name": "Maurits", "assignment": "W5D5 - Project - Lil_Playlist", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 655 ,  "name": "Maurits", "assignment": "W6D1-1", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 656 ,  "name": "Maurits", "assignment": "W6D2-1", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 657 ,  "name": "Maurits", "assignment": "W6D2 - Project - Eindopdracht", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 701 ,  "name": "Rahima", "assignment": "W4D1-Scrum", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 702 ,  "name": "Rahima", "assignment": "W1D1-1", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 703 ,  "name": "Rahima", "assignment": "W1D2-1", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 704 ,  "name": "Rahima", "assignment": "W1D2-2", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 705 ,  "name": "Rahima", "assignment": "W1D2-3", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 706 ,  "name": "Rahima", "assignment": "W1D2-4", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 707 ,  "name": "Rahima", "assignment": "W1D2-5", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 708 ,  "name": "Rahima", "assignment": "W1D3-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 709 ,  "name": "Rahima", "assignment": "W1D3-2", "ratingDifficulty": 2, "ratingFun":  4},  
  { "id": 711 ,  "name": "Rahima", "assignment": "W1D3-4", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 712 ,  "name": "Rahima", "assignment": "W1D3-5", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 713 ,  "name": "Rahima", "assignment": "W1D3 - Project - Guess-the-number", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 714 ,  "name": "Rahima", "assignment": "W1D4-1", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 715 ,  "name": "Rahima", "assignment": "W1D4 - Project - Kleurentoggle", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 716 ,  "name": "Rahima", "assignment": "W1D5 - Project - Galgje", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 717 ,  "name": "Rahima", "assignment": "W2D1-1", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 718 ,  "name": "Rahima", "assignment": "W2D1-2", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 719 ,  "name": "Rahima", "assignment": "W2D2-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 720 ,  "name": "Rahima", "assignment": "W2D2-2", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 721 ,  "name": "Rahima", "assignment": "W2D2-3", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 722 ,  "name": "Rahima", "assignment": "W2D3-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 723 ,  "name": "Rahima", "assignment": "W2D3-2", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 724 ,  "name": "Rahima", "assignment": "W2D3-3", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 725 ,  "name": "Rahima", "assignment": "W2D4-1", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 726 ,  "name": "Rahima", "assignment": "W2D4-2", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 727 ,  "name": "Rahima", "assignment": "W2D4-3", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 728 ,  "name": "Rahima", "assignment": "W2D5 - Project - Filmzoeker", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 729 ,  "name": "Rahima", "assignment": "W3D1-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 730 ,  "name": "Rahima", "assignment": "W3D1-2", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 731 ,  "name": "Rahima", "assignment": "W3D1-3", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 732 ,  "name": "Rahima", "assignment": "W3D1-4", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 733 ,  "name": "Rahima", "assignment": "W3D2-1", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 734 ,  "name": "Rahima", "assignment": "W3D2-2", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 735 ,  "name": "Rahima", "assignment": "W3D2-3", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 736 ,  "name": "Rahima", "assignment": "W3D3-1", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 737 ,  "name": "Rahima", "assignment": "W3D3-2", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 738 ,  "name": "Rahima", "assignment": "W3D3-3", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 739 ,  "name": "Rahima", "assignment": "W3D3-4", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 740 ,  "name": "Rahima", "assignment": "W3D4-1", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 741 ,  "name": "Rahima", "assignment": "W3D4-2", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 742 ,  "name": "Rahima", "assignment": "W3D5- Project Todo-List", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 743 ,  "name": "Rahima", "assignment": "W4D2-1", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 744 ,  "name": "Rahima", "assignment": "W4D2-2", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 745 ,  "name": "Rahima", "assignment": "W4D2-3", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 746 ,  "name": "Rahima", "assignment": "W4D2-4", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 747 ,  "name": "Rahima", "assignment": "W4D3-1", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 748 ,  "name": "Rahima", "assignment": "W4D3-2", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 749 ,  "name": "Rahima", "assignment": "W4D3-3", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 750 ,  "name": "Rahima", "assignment": "W4D3-4", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 751 ,  "name": "Rahima", "assignment": "W4D3-5", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 752 ,  "name": "Rahima", "assignment": "W4D3 - Project - Next-Level CSS", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 753 ,  "name": "Rahima", "assignment": "W5D4-1", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 754 ,  "name": "Rahima", "assignment": "W5D5 - Project - Lil_Playlist", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 755 ,  "name": "Rahima", "assignment": "W6D1-1", "ratingDifficulty": 4, "ratingFun": 4},
  { "id": 756 ,  "name": "Rahima", "assignment": "W6D2-1", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 757 ,  "name": "Rahima", "assignment": "W6D2 - Project - Eindopdracht", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 801 ,  "name": "Sandra", "assignment": "W4D1-Scrum", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 802 ,  "name": "Sandra", "assignment": "W1D1-1", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 803 ,  "name": "Sandra", "assignment": "W1D2-1", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 804 ,  "name": "Sandra", "assignment": "W1D2-2", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 805 ,  "name": "Sandra", "assignment": "W1D2-3", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 806 ,  "name": "Sandra", "assignment": "W1D2-4", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 807 ,  "name": "Sandra", "assignment": "W1D2-5", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 808 ,  "name": "Sandra", "assignment": "W1D3-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 809 ,  "name": "Sandra", "assignment": "W1D3-2", "ratingDifficulty": 1, "ratingFun":  1},  
  { "id": 811 ,  "name": "Sandra", "assignment": "W1D3-4", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 812 ,  "name": "Sandra", "assignment": "W1D3-5", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 813 ,  "name": "Sandra", "assignment": "W1D3 - Project - Guess-the-number", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 814 ,  "name": "Sandra", "assignment": "W1D4-1", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 815 ,  "name": "Sandra", "assignment": "W1D4 - Project - Kleurentoggle", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 816 ,  "name": "Sandra", "assignment": "W1D5 - Project - Galgje", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 817 ,  "name": "Sandra", "assignment": "W2D1-1", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 818 ,  "name": "Sandra", "assignment": "W2D1-2", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 819 ,  "name": "Sandra", "assignment": "W2D2-1", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 820 ,  "name": "Sandra", "assignment": "W2D2-2", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 821 ,  "name": "Sandra", "assignment": "W2D2-3", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 822 ,  "name": "Sandra", "assignment": "W2D3-1", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 823 ,  "name": "Sandra", "assignment": "W2D3-2", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 824 ,  "name": "Sandra", "assignment": "W2D3-3", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 825 ,  "name": "Sandra", "assignment": "W2D4-1", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 826 ,  "name": "Sandra", "assignment": "W2D4-2", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 827 ,  "name": "Sandra", "assignment": "W2D4-3", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 828 ,  "name": "Sandra", "assignment": "W2D5 - Project - Filmzoeker", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 829 ,  "name": "Sandra", "assignment": "W3D1-1", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 830 ,  "name": "Sandra", "assignment": "W3D1-2", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 831 ,  "name": "Sandra", "assignment": "W3D1-3", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 832 ,  "name": "Sandra", "assignment": "W3D1-4", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 833 ,  "name": "Sandra", "assignment": "W3D2-1", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 834 ,  "name": "Sandra", "assignment": "W3D2-2", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 835 ,  "name": "Sandra", "assignment": "W3D2-3", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 836 ,  "name": "Sandra", "assignment": "W3D3-1", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 837 ,  "name": "Sandra", "assignment": "W3D3-2", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 838 ,  "name": "Sandra", "assignment": "W3D3-3", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 839 ,  "name": "Sandra", "assignment": "W3D3-4", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 840 ,  "name": "Sandra", "assignment": "W3D4-1", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 841 ,  "name": "Sandra", "assignment": "W3D4-2", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 842 ,  "name": "Sandra", "assignment": "W3D5- Project Todo-List", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 843 ,  "name": "Sandra", "assignment": "W4D2-1", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 844 ,  "name": "Sandra", "assignment": "W4D2-2", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 845 ,  "name": "Sandra", "assignment": "W4D2-3", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 846 ,  "name": "Sandra", "assignment": "W4D2-4", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 847 ,  "name": "Sandra", "assignment": "W4D3-1", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 848 ,  "name": "Sandra", "assignment": "W4D3-2", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 849 ,  "name": "Sandra", "assignment": "W4D3-3", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 850 ,  "name": "Sandra", "assignment": "W4D3-4", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 851 ,  "name": "Sandra", "assignment": "W4D3-5", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 852 ,  "name": "Sandra", "assignment": "W4D3 - Project - Next-Level CSS", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 853 ,  "name": "Sandra", "assignment": "W5D4-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 854 ,  "name": "Sandra", "assignment": "W5D5 - Project - Lil_Playlist", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 855 ,  "name": "Sandra", "assignment": "W6D1-1", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 856 ,  "name": "Sandra", "assignment": "W6D2-1", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 857 ,  "name": "Sandra", "assignment": "W6D2 - Project - Eindopdracht", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 901 ,  "name": "Wietske", "assignment": "W4D1-Scrum", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 902 ,  "name": "Wietske", "assignment": "W1D1-1", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 903 ,  "name": "Wietske", "assignment": "W1D2-1", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 904 ,  "name": "Wietske", "assignment": "W1D2-2", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 905 ,  "name": "Wietske", "assignment": "W1D2-3", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 906 ,  "name": "Wietske", "assignment": "W1D2-4", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 907 ,  "name": "Wietske", "assignment": "W1D2-5", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 908 ,  "name": "Wietske", "assignment": "W1D3-1", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 909 ,  "name": "Wietske", "assignment": "W1D3-2", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 911 ,  "name": "Wietske", "assignment": "W1D3-4", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 912 ,  "name": "Wietske", "assignment": "W1D3-5", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 913 ,  "name": "Wietske", "assignment": "W1D3 - Project - Guess-the-number", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 914 ,  "name": "Wietske", "assignment": "W1D4-1", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 915 ,  "name": "Wietske", "assignment": "W1D4 - Project - Kleurentoggle", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 916 ,  "name": "Wietske", "assignment": "W1D5 - Project - Galgje", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 917 ,  "name": "Wietske", "assignment": "W2D1-1", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 918 ,  "name": "Wietske", "assignment": "W2D1-2", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 919 ,  "name": "Wietske", "assignment": "W2D2-1", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 920 ,  "name": "Wietske", "assignment": "W2D2-2", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 921 ,  "name": "Wietske", "assignment": "W2D2-3", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 922 ,  "name": "Wietske", "assignment": "W2D3-1", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 923 ,  "name": "Wietske", "assignment": "W2D3-2", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 924 ,  "name": "Wietske", "assignment": "W2D3-3", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 925 ,  "name": "Wietske", "assignment": "W2D4-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 926 ,  "name": "Wietske", "assignment": "W2D4-2", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 927 ,  "name": "Wietske", "assignment": "W2D4-3", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 928 ,  "name": "Wietske", "assignment": "W2D5 - Project - Filmzoeker", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 929 ,  "name": "Wietske", "assignment": "W3D1-1", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 930 ,  "name": "Wietske", "assignment": "W3D1-2", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 931 ,  "name": "Wietske", "assignment": "W3D1-3", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 932 ,  "name": "Wietske", "assignment": "W3D1-4", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 933 ,  "name": "Wietske", "assignment": "W3D2-1", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 934 ,  "name": "Wietske", "assignment": "W3D2-2", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 935 ,  "name": "Wietske", "assignment": "W3D2-3", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 936 ,  "name": "Wietske", "assignment": "W3D3-1", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 937 ,  "name": "Wietske", "assignment": "W3D3-2", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 938 ,  "name": "Wietske", "assignment": "W3D3-3", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 939 ,  "name": "Wietske", "assignment": "W3D3-4", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 940 ,  "name": "Wietske", "assignment": "W3D4-1", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 941 ,  "name": "Wietske", "assignment": "W3D4-2", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 942 ,  "name": "Wietske", "assignment": "W3D5- Project Todo-List", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 943 ,  "name": "Wietske", "assignment": "W4D2-1", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 944 ,  "name": "Wietske", "assignment": "W4D2-2", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 945 ,  "name": "Wietske", "assignment": "W4D2-3", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 946 ,  "name": "Wietske", "assignment": "W4D2-4", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 947 ,  "name": "Wietske", "assignment": "W4D3-1", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 948 ,  "name": "Wietske", "assignment": "W4D3-2", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 949 ,  "name": "Wietske", "assignment": "W4D3-3", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 950 ,  "name": "Wietske", "assignment": "W4D3-4", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 951 ,  "name": "Wietske", "assignment": "W4D3-5", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 952 ,  "name": "Wietske", "assignment": "W4D3 - Project - Next-Level CSS", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 953 ,  "name": "Wietske", "assignment": "W5D4-1", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 954 ,  "name": "Wietske", "assignment": "W5D5 - Project - Lil_Playlist", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 955 ,  "name": "Wietske", "assignment": "W6D1-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 956 ,  "name": "Wietske", "assignment": "W6D2-1", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 957 ,  "name": "Wietske", "assignment": "W6D2 - Project - Eindopdracht", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 1001 , "name": "Storm", "assignment": "W4D1-Scrum", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 1002 , "name": "Storm", "assignment": "W1D1-1", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 1003 , "name": "Storm", "assignment": "W1D2-1", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 1004 , "name": "Storm", "assignment": "W1D2-2", "ratingDifficulty": 1, "ratingFun":  3},
  { "id": 1005 , "name": "Storm", "assignment": "W1D2-3", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 1006 , "name": "Storm", "assignment": "W1D2-4", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 1007 , "name": "Storm", "assignment": "W1D2-5", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 1008 , "name": "Storm", "assignment": "W1D3-1", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 1009 , "name": "Storm", "assignment": "W1D3-2", "ratingDifficulty": 1, "ratingFun":  1},  
  { "id": 1011 , "name": "Storm", "assignment": "W1D3-4", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 1012 , "name": "Storm", "assignment": "W1D3-5", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 1013 , "name": "Storm", "assignment": "W1D3 - Project - Guess-the-number", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 1014 , "name": "Storm", "assignment": "W1D4-1", "ratingDifficulty": 4, "ratingFun":  2},
  { "id": 1015 , "name": "Storm", "assignment": "W1D4 - Project - Kleurentoggle", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 1016 , "name": "Storm", "assignment": "W1D5 - Project - Galgje", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 1017 , "name": "Storm", "assignment": "W2D1-1", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 1018 , "name": "Storm", "assignment": "W2D1-2", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 1019 , "name": "Storm", "assignment": "W2D2-1", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 1020 , "name": "Storm", "assignment": "W2D2-2", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 1021 , "name": "Storm", "assignment": "W2D2-3", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 1022 , "name": "Storm", "assignment": "W2D3-1", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 1023 , "name": "Storm", "assignment": "W2D3-2", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 1024 , "name": "Storm", "assignment": "W2D3-3", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 1025 , "name": "Storm", "assignment": "W2D4-1", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 1026 , "name": "Storm", "assignment": "W2D4-2", "ratingDifficulty": 4, "ratingFun":  3},
  { "id": 1027 , "name": "Storm", "assignment": "W2D4-3", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 1028 , "name": "Storm", "assignment": "W2D5 - Project - Filmzoeker", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 1029 , "name": "Storm", "assignment": "W3D1-1", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 1030 , "name": "Storm", "assignment": "W3D1-2", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 1031 , "name": "Storm", "assignment": "W3D1-3", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 1032 , "name": "Storm", "assignment": "W3D1-4", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 1033 , "name": "Storm", "assignment": "W3D2-1", "ratingDifficulty": 1, "ratingFun":  4},
  { "id": 1034 , "name": "Storm", "assignment": "W3D2-2", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 1035 , "name": "Storm", "assignment": "W3D2-3", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 1036 , "name": "Storm", "assignment": "W3D3-1", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 1037 , "name": "Storm", "assignment": "W3D3-2", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 1038 , "name": "Storm", "assignment": "W3D3-3", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 1039 , "name": "Storm", "assignment": "W3D3-4", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 1040 , "name": "Storm", "assignment": "W3D4-1", "ratingDifficulty": 2, "ratingFun":  4},
  { "id": 1041 , "name": "Storm", "assignment": "W3D4-2", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 1042 , "name": "Storm", "assignment": "W3D5- Project Todo-List", "ratingDifficulty": 3, "ratingFun":  2},
  { "id": 1043 , "name": "Storm", "assignment": "W4D2-1", "ratingDifficulty": 2, "ratingFun":  1},
  { "id": 1044 , "name": "Storm", "assignment": "W4D2-2", "ratingDifficulty": 3, "ratingFun":  3},
  { "id": 1045 , "name": "Storm", "assignment": "W4D2-3", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 1046 , "name": "Storm", "assignment": "W4D2-4", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 1047 , "name": "Storm", "assignment": "W4D3-1", "ratingDifficulty": 3, "ratingFun":  4},
  { "id": 1048 , "name": "Storm", "assignment": "W4D3-2", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 1049 , "name": "Storm", "assignment": "W4D3-3", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 1050 , "name": "Storm", "assignment": "W4D3-4", "ratingDifficulty": 3, "ratingFun":  1},
  { "id": 1051 , "name": "Storm", "assignment": "W4D3-5", "ratingDifficulty": 2, "ratingFun":  3},
  { "id": 1052 , "name": "Storm", "assignment": "W4D3 - Project - Next-Level CSS", "ratingDifficulty": 4, "ratingFun":  1},
  { "id": 1053 , "name": "Storm", "assignment": "W5D4-1", "ratingDifficulty": 2, "ratingFun":  2},
  { "id": 1054 , "name": "Storm", "assignment": "W5D5 - Project - Lil_Playlist", "ratingDifficulty": 1, "ratingFun":  2},
  { "id": 1055 , "name": "Storm", "assignment": "W6D1-1", "ratingDifficulty": 4, "ratingFun":  4},
  { "id": 1056 , "name": "Storm", "assignment": "W6D2-1", "ratingDifficulty": 1, "ratingFun":  1},
  { "id": 1057 , "name": "Storm", "assignment": "W6D2 - Project - Eindopdracht", "ratingDifficulty": 3, "ratingFun":  3}

];

export default StudentData